// Directory data transcribed from the CPGRAMS public directory pages
// (pgportal.gov.in/Home/NodalPgOfficers, /NodalPgOfficersState, /NodalAuthorityForAppeal).
// Captured on 2026-08-29.
//
// Row counts (source table -> captured):
//   Central Nodal PG Officers  : 92 -> 92 (complete)
//   State/UT Nodal PG Officers : 37 -> 37 (complete)
//   Nodal Appellate Authorities: 88 -> 88 (complete)
//
// The source tables are fully server-rendered (no pagination on the server response),
// so every row published on each page is included here. Nothing was truncated.
//
// Transcription notes:
//   - The portal publishes e-mail addresses obfuscated as "name[at]domain[dot]in".
//     These are de-obfuscated here to "name@domain.in"; no address was otherwise altered.
//   - Whitespace is normalised and HTML entities decoded. Line-wrap artefacts that exist
//     in the published address strings (e.g. stray spaces inside words) are left as published.
//   - Blank source fields are represented as an empty string. No value was invented.

export type NodalOfficer = {
  id: string; // stable kebab-case slug of the org name
  srNo: string; // "S.No." as printed on the source page
  org: string; // ministry / department / organisation / state or UT name
  name: string;
  designation: string;
  phone: string;
  email: string;
  address: string;
};

export type AppellateAuthority = {
  id: string; // stable kebab-case slug of the org name
  srNo: string; // "S.No." as printed on the source page
  org: string; // ministry / department / organisation
  name: string;
  designation: string;
  phone: string;
  email: string;
  address: string;
};

/** Nodal Public Grievance Officers of Central Ministries / Departments / Organisations. */
export const CENTRAL_NODAL: NodalOfficer[] = [
  {
    id: "administrative-reforms-and-public-grievances-pg-division",
    srNo: "1",
    org: "Administrative Reforms and Public Grievances - PG Division",
    name: "Sardendu Kumar Pandey",
    designation: "Director",
    phone: "01123401455",
    email: "Director-pg@gov.in",
    address: "5th Floor Sardar Patel Bhawan Sansad Marg, New Delhi",
  },
  {
    id: "agriculture-and-farmers-welfare",
    srNo: "2",
    org: "Agriculture and Farmers Welfare",
    name: "Shri Rajesh Kumar",
    designation: "Deputy Secretary PG",
    phone: "01123074238",
    email: "rajesh.kumar67@nic.in",
    address: "Room No. 434 Krishi Bhavan New Delhi",
  },
  {
    id: "agriculture-research-and-education",
    srNo: "3",
    org: "Agriculture Research and Education",
    name: "Narendra Kumar",
    designation: "Deputy Secretary",
    phone: "01123046678",
    email: "narendra.kumar74@nic.in",
    address: "R No. 207, Krishi Bhawan, New Delhi",
  },
  {
    id: "animal-husbandry-dairying",
    srNo: "4",
    org: "Animal Husbandry, Dairying",
    name: "RPS Rathore",
    designation: "Director",
    phone: "01123385797",
    email: "r.rathore@gov.in",
    address: "Room No. 297, 2nd Floor, Krishi Bhavan, New Delhi",
  },
  {
    id: "atomic-energy",
    srNo: "5",
    org: "Atomic Energy",
    name: "Shri K.V. Madhavadas",
    designation: "Deputy Secretary",
    phone: "02222862516",
    email: "dsscs@dae.gov.in",
    address: "D/o Atomic Energy, Anushakti Bhavan, 3rd Floor, C S M Marg, MUMBAI",
  },
  {
    id: "ayush",
    srNo: "6",
    org: "Ayush",
    name: "Dr Srinivas Rao Chinta",
    designation: "Joint Adviser",
    phone: "01124656948",
    email: "ayush-cdn@gov.in",
    address: "AYUSH BHAWAN, GPO COMPLEX,B BLOCK,INA ,NEW DELHI",
  },
  {
    id: "bio-technology",
    srNo: "7",
    org: "Bio Technology",
    name: "Rajesh Kumar Singh",
    designation: "Director",
    phone: "01124363656",
    email: "rajesh.kumar@gov.in",
    address: "Room No. 504, Block No. 3, 5th Floor, CGO Complex, Lodi Road, New Delhi",
  },
  {
    id: "central-board-of-direct-taxes-income-tax",
    srNo: "8",
    org: "Central Board of Direct Taxes (Income Tax)",
    name: "Swapna Devireddy",
    designation: "Addl. Director of Income Tax TPS-II",
    phone: "01123416133",
    email: "delhi.addldit.eservices@incometax.gov.in",
    address: "4th Floor, Mayur Bhawan, Connaught Circus, New Delhi",
  },
  {
    id: "central-board-of-excise-and-customs",
    srNo: "9",
    org: "Central Board of Excise and Customs",
    name: "Ms. Ranjana Chaudhary",
    designation: "Joint Director",
    phone: "01123370576",
    email: "ranjana.chaudhary@gov.in",
    address: "Directorate General of Taxpayer Services, Room no 168, Ist Floor, Central Revenue Building, I.P. Es tate, New Delhi",
  },
  {
    id: "chemicals-and-petrochemicals",
    srNo: "10",
    org: "Chemicals and Petrochemicals",
    name: "Shri. Chitvan Singh Dhillon",
    designation: "Deputy Director",
    phone: "01123386083",
    email: "chitvan.dhillon@gov.in",
    address: "Room No. 223 A , Shastri Bhavan, New Delhi",
  },
  {
    id: "civil-aviation",
    srNo: "11",
    org: "Civil Aviation",
    name: "Shri Sudhansu Sekhar Mishra",
    designation: "Deputy Secretary and PGO",
    phone: "01124610364",
    email: "ss.mishra@nic.in",
    address: "Room. No.C-27, Ground Floor, B-Block, Rajiv Gandhi Bhawan, Safdarjung Airport, New Delhi",
  },
  {
    id: "coal",
    srNo: "12",
    org: "Coal",
    name: "Smt Chetna Shukla",
    designation: "Deputy Director General",
    phone: "01124699948",
    email: "chetna.shukla@nic.in",
    address: "Ministry of Coal, 5rd Floor, Lok Nayak Bhawan, New Delhi",
  },
  {
    id: "commerce",
    srNo: "13",
    org: "Commerce",
    name: "Shri Govind Mishra",
    designation: "Deputy Secretary",
    phone: "01123038552",
    email: "jspg-doc@gov.in",
    address: "Vanijya Bhavan, New Delhi",
  },
  {
    id: "consumer-affairs",
    srNo: "14",
    org: "Consumer Affairs",
    name: "Shri Prashant Dubey",
    designation: "Director",
    phone: "01123384390",
    email: "dspg-ca@gov.in",
    address: "Room No.372 - B Krishi Bhavan New Delhi",
  },
  {
    id: "cooperation",
    srNo: "15",
    org: "Cooperation",
    name: "Shri Goonjan Kumar",
    designation: "Joint Director",
    phone: "01120849009",
    email: "dir.cd3-coop@gov.in",
    address: "Atal Akshay Urja Bhawan, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "corporate-affairs",
    srNo: "16",
    org: "Corporate Affairs",
    name: "C.M. Karlmarx",
    designation: "Joint Director",
    phone: "01123385285",
    email: "cm.karlmarx@gov.in",
    address: "Kota House, New Delhi",
  },
  {
    id: "culture",
    srNo: "17",
    org: "Culture",
    name: "Randheep Thakur",
    designation: "Director",
    phone: "01124014233",
    email: "randheep.thakur@nic.in",
    address: "Room No. 220075, Kartavya Bhawan-II, Ministry of Culture, New Delhi",
  },
  {
    id: "defence",
    srNo: "18",
    org: "Defence",
    name: "Shri Manish Tripathi",
    designation: "JS MIS",
    phone: "01123017828",
    email: "usdpg-mod@gov.in",
    address: "Room No. 198A, South Block New Delhi",
  },
  {
    id: "defence-finance",
    srNo: "19",
    org: "Defence Finance",
    name: "Dr. Ishita Ganguli Tripathy",
    designation: "Addl. Financial Advisor and Joint Secretary",
    phone: "01124014414",
    email: "addl.fa1-dad@gov.in",
    address: "Room No 26039, 6th Floor Kartavya Bhawan-2, New Delhi",
  },
  {
    id: "defence-production",
    srNo: "20",
    org: "Defence Production",
    name: "Dr. Meetu Agarwal",
    designation: "Director Coord DDP",
    phone: "01124015526",
    email: "dir-coord@ddpmod.gov.in",
    address: "Room No. 25103, Kartavya Bhawan- 2, New Delhi",
  },
  {
    id: "defence-research-and-development",
    srNo: "21",
    org: "Defence Research and Development",
    name: "Dr. Sanjai Kumar Dwivedi",
    designation: "Sc G and Director Human Resource & Vigilance",
    phone: "01123007218",
    email: "director-dhrv@gov.in",
    address: "DRDO HQrs, Min of Defence, Room No. 217, DRDO Bhawan, Rajaji Marg, New Delhi",
  },
  {
    id: "development-of-north-eastern-region",
    srNo: "22",
    org: "Development of North Eastern Region",
    name: "Shri Jitendra R. Gaikwad",
    designation: "Joint Secretary",
    phone: "01121411638",
    email: "JR.Gaikwad@nic.in",
    address: "Room No. 11 Block- 12A Jodhpur Officers Hostel, Pandara Park",
  },
  {
    id: "drinking-water-and-sanitation",
    srNo: "23",
    org: "Drinking Water and Sanitation",
    name: "Shri Arun Kumar Kembhavi",
    designation: "Director",
    phone: "01124364112",
    email: "arunkumar.kembhavi@gov.in",
    address: "4th Floor, Pt. Deendayal Antyodhya Bhawan, CGO Complex,",
  },
  {
    id: "earth-sciences",
    srNo: "24",
    org: "Earth Sciences",
    name: "RAJENDRA KUMAR KUMHAR",
    designation: "Director",
    phone: "01124669718",
    email: "rajendrakumhar@ord.gov.in",
    address: "Room No. 305 3rd Floor, Prithvi Bhawan Opp. India Habitat Centre, Lodi Road, New Delhi",
  },
  {
    id: "economic-affairs",
    srNo: "25",
    org: "Economic Affairs",
    name: "Mr. Sourabh Kumar",
    designation: "Under Secretary",
    phone: "01124012870",
    email: "sourabhkumar3.pb@nic.in",
    address: "Room No. 15051 Work Hall, 5th Floor, A - Wing, Kartavya Bhavan - 1, New Delhi-110001",
  },
  {
    id: "electronics-and-information-technology",
    srNo: "26",
    org: "Electronics & Information Technology",
    name: "Sudeep Shrivastava",
    designation: "Joint Secretary and GC",
    phone: "01124301815",
    email: "js.ssoffice@meity.gov.in",
    address: "6, CGO Complex, Electronics Niketan, New Delhi",
  },
  {
    id: "empowerment-of-persons-with-disabilities",
    srNo: "27",
    org: "Empowerment of Persons with Disabilities",
    name: "Ipsita Mitra",
    designation: "Deputy Secretary",
    phone: "01124369066",
    email: "cpgramsdepwd@gmail.com",
    address: "5th Floor, Pt. Deendayal Antyodaya Bhawan, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "environment-forest-and-climate-change",
    srNo: "28",
    org: "Environment, Forest and Climate Change",
    name: "Shri Debabrata Das",
    designation: "Deputy Secretary",
    phone: "01120819284",
    email: "debabrata.d13@nic.in",
    address: "3rd Floor, Jal Wing, Indira Paryavaran Bhavan, Jor Bagh New Delhi",
  },
  {
    id: "ex-servicemen-welfare",
    srNo: "29",
    org: "Ex Servicemen Welfare",
    name: "Brig IP Singh",
    designation: "Brig ESW",
    phone: "01124014705",
    email: "ds-pg@desw.gov.in",
    address: "6th Floor, Kartavya Bhavan-2, New Delhi",
  },
  {
    id: "expenditure",
    srNo: "30",
    org: "Expenditure",
    name: "Shri Sunil Kumar",
    designation: "Deputy Secretary",
    phone: "01123095705",
    email: "sunilkumar0970@nic.in",
    address: "Room No. 48E, North Block, New Delhi",
  },
  {
    id: "external-affairs",
    srNo: "31",
    org: "External Affairs",
    name: "Ms. Esha Srivastava",
    designation: "Joint Secretary",
    phone: "01123384529",
    email: "",
    address: "CPV Division, Patiala House Annexe, Tilak Marg, New Delhi",
  },
  {
    id: "fertilizers",
    srNo: "32",
    org: "Fertilizers",
    name: "Mohan Lal Meena",
    designation: "DS Coordination",
    phone: "01123388064",
    email: "mohanlal.meena70@nic.in",
    address: "Shastri Bhawan, New Delhi",
  },
  {
    id: "financial-services-banking-division",
    srNo: "33",
    org: "Financial Services (Banking Division)",
    name: "SHRI SWAPNIL AGRAWAL",
    designation: "DIRECTOR",
    phone: "01123346785",
    email: "dir.sa-dfs@gov.in",
    address: "3RD Floor, Jeevan Deep Building Building, Sansad Marg New Delhi",
  },
  {
    id: "financial-services-insurance-division",
    srNo: "34",
    org: "Financial Services (Insurance Division)",
    name: "Sh SWAPNIL AGRAWAL",
    designation: "DIRECTOR",
    phone: "01123346785",
    email: "dir.sa-dfs@gov.in",
    address: "3RD Floor,Jeevan Deep Building Building, Sansad Marg New Delhi",
  },
  {
    id: "financial-services-pension-reforms",
    srNo: "35",
    org: "Financial Services (Pension Reforms)",
    name: "Shri. Swapnil Agrawal",
    designation: "Director",
    phone: "01123748786",
    email: "dir.sa-dfs@gov.in",
    address: "3rd Floor, Jeevandeep Building New Delhi",
  },
  {
    id: "fisheries",
    srNo: "36",
    org: "Fisheries",
    name: "Pumzalal Pulamte",
    designation: "Deputy Secretary",
    phone: "01123710006",
    email: "p.pulamte@nic.in",
    address: "First floor Chanderlok Building, Janpath New Delhi",
  },
  {
    id: "food-and-public-distribution",
    srNo: "37",
    org: "Food and Public Distribution",
    name: "Ms. Nandita Mishra",
    designation: "Senior Economic Adviser",
    phone: "01123070371",
    email: "nandita.mishra@nic.in",
    address: "Room No. 194 Krishi Bhavan New Delhi",
  },
  {
    id: "food-processing-industries",
    srNo: "38",
    org: "Food Processing Industries",
    name: "Shri. Preetpal Singh",
    designation: "Joint Secretary",
    phone: "01126492476",
    email: "preetpal.singh@nic.in",
    address: "Panchsheel Bhawan, August Kranti Marg, New Delhi",
  },
  {
    id: "health-and-family-welfare",
    srNo: "39",
    org: "Health & Family Welfare",
    name: "Ashok Kumar Gupta",
    designation: "Director",
    phone: "01124013421",
    email: "ashok.kgupta@nic.in",
    address: "Room No. 110050",
  },
  {
    id: "health-research",
    srNo: "40",
    org: "Health Research",
    name: "Shri Pradyumn Kumar",
    designation: "Under Secretary",
    phone: "01123736218",
    email: "pradyumn.kumar@nic.in",
    address: "Room No. Indian Red Cross Society Building, 1, Red Cross Road, NEW DELHI",
  },
  {
    id: "heavy-industry",
    srNo: "41",
    org: "Heavy Industry",
    name: "Brijesh Kumar",
    designation: "Joint Director",
    phone: "01126112329",
    email: "jd.pg.mhi@gov.in",
    address: "GPOA-3, R. No. 2519, Neta ji Nagar, New Delhi",
  },
  {
    id: "higher-education",
    srNo: "42",
    org: "Higher Education",
    name: "Dharmendra Kr Himanshu",
    designation: "DS",
    phone: "01123384721",
    email: "dk.himanshu@nic.in",
    address: "Room No. 6,West Block 1,wing 6, R K Puram, 2nd Flo or,D/o Higher Education,Ministry of Education, New Delhi",
  },
  {
    id: "home-affairs",
    srNo: "43",
    org: "Home Affairs",
    name: "DS Coord",
    designation: "DS coord",
    phone: "01123438002",
    email: "dircoord-mha@nic.in",
    address: "5th Floor, Media Wing, NDCC - II Building New Delhi",
  },
  {
    id: "housing-and-urban-affairs",
    srNo: "44",
    org: "Housing and Urban Affairs",
    name: "Sh. SHANKAR PRASAD CHOUDHARY",
    designation: "DEPUTY SECRETARY",
    phone: "01123783000",
    email: "shankar.pc@nic.in",
    address: "Room No. 0816, 8th Floor, Sankalp Bhawan",
  },
  {
    id: "information-and-broadcasting",
    srNo: "45",
    org: "Information and Broadcasting",
    name: "Suresh Kumar Meena",
    designation: "Deputy Secretary",
    phone: "01124015833",
    email: "suresh.kumar150873@gov.in",
    address: "Room No. 22067, Kartavya Bhawan 2, New Delhi",
  },
  {
    id: "investment-and-public-asset-management",
    srNo: "46",
    org: "Investment & Public Asset Management",
    name: "Shri Sudhir Shyam",
    designation: "Economic Adviser",
    phone: "01124368037",
    email: "sudhir.s@nic.in",
    address: "Room No. 520, 5th Floor Block No.14 CGO Complex, Lodhi Road New Delhi",
  },
  {
    id: "justice",
    srNo: "47",
    org: "Justice",
    name: "G MUthuraja",
    designation: "JS",
    phone: "01123070673",
    email: "drj1-doj@gov.in",
    address: "Jaisalmer House, Mansingh Road, New Delhi",
  },
  {
    id: "labour-and-employment",
    srNo: "48",
    org: "Labour and Employment",
    name: "Shri G. Sajith Kumar",
    designation: "Deputy Secretary and Nodal PGO",
    phone: "01123719054",
    email: "sajith.edu@nic.in",
    address: "Room No. 505, Fifth Floor, Shram Shakti Bhavan, Rafi Marg, New Delhi.",
  },
  {
    id: "land-resources",
    srNo: "49",
    org: "Land Resources",
    name: "Vivek Narayan",
    designation: "Deputy Secretary",
    phone: "01124011524",
    email: "vivek.narayan14@nic.in",
    address: "Work Hall No.32007, 2nd Floor, Kartavya Bhawan-3, New Delhi-110001",
  },
  {
    id: "legal-affairs",
    srNo: "50",
    org: "Legal Affairs",
    name: "Devanshu Kumar",
    designation: "Public Grievance Officer",
    phone: "01123383634",
    email: "pgcell.dla@gov.in",
    address: "4th Floor, A-Wing, Shastri Bhawan, Dr. Rajendra Prasad Rd. New Delhi",
  },
  {
    id: "legislative-department",
    srNo: "51",
    org: "Legislative Department",
    name: "Rajesh Kumar",
    designation: "Deputy Secretary",
    phone: "01124016043",
    email: "admin1ld@nic.in",
    address: "Room No.24050, 4th Floor, Kartavya Bhavan-2, New Delhi",
  },
  {
    id: "micro-small-and-medium-enterprises",
    srNo: "52",
    org: "Micro Small and Medium Enterprises",
    name: "Md. Salik Parwaiz",
    designation: "Director",
    phone: "01124011292",
    email: "salik.parwaiz@nic.in",
    address: "32063, Kartavya Bhavan 3, 2nd Floor, New Delhi",
  },
  {
    id: "military-affairs",
    srNo: "53",
    org: "Military Affairs",
    name: "Parag Kabat",
    designation: "Director Coord",
    phone: "01123013416",
    email: "dircoord.ec-dma@gov.in",
    address: "Room No 143 Sena Bhawan New Delhi",
  },
  {
    id: "mines",
    srNo: "54",
    org: "Mines",
    name: "Shri Rajesh Kumar Ner",
    designation: "Section Officer - PG&PI",
    phone: "01126773646",
    email: "pgpi-mom@gov.in",
    address: "Zone 3, 4th Floor, GPOA-3 Building, Netaji Nagar, New Delhi",
  },
  {
    id: "minority-affairs",
    srNo: "55",
    org: "Minority Affairs",
    name: "Shri T.K. Das",
    designation: "Deputy Secretary",
    phone: "01124364277",
    email: "dsrti-mma@gov.in",
    address: "Pt. Deendayal Antyodaya Bhawan, 11th Floor,CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "new-and-renewable-energy",
    srNo: "56",
    org: "New and Renewable Energy",
    name: "Mr. M. Mukherjee",
    designation: "Director",
    phone: "01124303164",
    email: "m.mukerjee@gov.in",
    address: "Room No. 309, Atal Akshaya Urja Bhavan, Opp. CGO Complex, Lodi Road, N Delhi",
  },
  {
    id: "niti-aayog",
    srNo: "57",
    org: "NITI Aayog",
    name: "VINOD KUMAR",
    designation: "DS",
    phone: "01123042475",
    email: "vinod.kumar@nic.in",
    address: "Room No. 404, NITI Aayog, Sansad Marg, New Delhi",
  },
  {
    id: "o-o-the-comptroller-and-auditor-general-of-india",
    srNo: "58",
    org: "O/o the Comptroller & Auditor General of India",
    name: "Sumeet Kumar",
    designation: "Assistant Comptroller and Auditor General",
    phone: "01123509303",
    email: "acn@cag.gov.in",
    address: "9, Deen Dayal Upadhayaya Marg, New Delhi",
  },
  {
    id: "official-language",
    srNo: "59",
    org: "Official Language",
    name: "Satinder Kaur",
    designation: "Deputy Secretary",
    phone: "01123438155",
    email: "s.kaur68@nic.in",
    address: "NDCC-II Bhawan, Jai Singh Road New Delhi",
  },
  {
    id: "panchayati-raj",
    srNo: "60",
    org: "Panchayati Raj",
    name: "Shri Prashant Kumar",
    designation: "Under Secretary",
    phone: "01123725314",
    email: "prashant.rth@nic.in",
    address: "Ministry of Panchayati Raj, Tower II, 9th Floor, Jeevan Bharti Building, New Delhi",
  },
  {
    id: "parliamentary-affairs",
    srNo: "61",
    org: "Parliamentary Affairs",
    name: "S. S. Patra",
    designation: "Deputy Secretary",
    phone: "01123083876",
    email: "ss.patra@nic.in",
    address: "S-59, Parliament House, New Delhi",
  },
  {
    id: "pensions-and-pensioners-welfare",
    srNo: "62",
    org: "Pensions and Pensioners Welfare",
    name: "Sanjay Bharti",
    designation: "Under Secretary CPENGRAMS",
    phone: "01124644632",
    email: "sanjay.bharti84@gov.in",
    address: "3rd Floor, Lok Nayak Bhawan, Khan Market",
  },
  {
    id: "personnel-and-training",
    srNo: "63",
    org: "Personnel and Training",
    name: "Dilip Kumar Jha",
    designation: "Deputy Secretary",
    phone: "01124010499",
    email: "dk.jha@nic.in",
    address: "31010 , DOPT, Kartavya Bhavan - 03, New Delhi",
  },
  {
    id: "petroleum-and-natural-gas",
    srNo: "64",
    org: "Petroleum and Natural Gas",
    name: "Shri Aditya Shekhar Singh",
    designation: "Deputy Secretary",
    phone: "01124011194",
    email: "aditya.singh@nic.in",
    address: "Room No. FF 31112 Kartavya Bhawan 3 New Delhi",
  },
  {
    id: "pharmaceutical",
    srNo: "65",
    org: "Pharmaceutical",
    name: "Vijay Kumar Srivastava",
    designation: "Director",
    phone: "01123327718",
    email: "vijayk.srivastava25@nic.in",
    address: "Janpath Bhawan",
  },
  {
    id: "posts",
    srNo: "66",
    org: "Posts",
    name: "Shri Rupesh Pal",
    designation: "ADG PG",
    phone: "01123096087",
    email: "ddgpgq@indiapost.gov.in",
    address: "Room No. 236H1, Dak Bhavan, Parliament Street New Delhi",
  },
  {
    id: "power",
    srNo: "67",
    org: "Power",
    name: "Amarjit Singh",
    designation: "Director - Public Grievance and RTI",
    phone: "011230633454",
    email: "singh.amarjit@gov.in",
    address: "2nd Floor, F Wing, Nirman Bhawan, Maulana Azad Rd, Rajpath Area, New Delhi",
  },
  {
    id: "promotion-of-industry-and-internal-trade",
    srNo: "68",
    org: "Promotion of Industry and Internal Trade",
    name: "DALIP KUMAR CHAWLA",
    designation: "Deputy Secretary",
    phone: "01123062947",
    email: "dalip.chawla@gov.in",
    address: "Room No. 226, ,Department for Promotion of Industry and Internal Trade, Udyog Bhavan, New Delhi",
  },
  {
    id: "public-enterprises",
    srNo: "69",
    org: "Public Enterprises",
    name: "Muni Ram Meena",
    designation: "Director",
    phone: "01124362770",
    email: "munirammeena@ord.gov.in",
    address: "Room No. 422, Block No. 14, Public Enterprises Bhawan, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "railways-railway-board",
    srNo: "70",
    org: "Railways, ( Railway Board)",
    name: "RATNESH KUMAR JHA",
    designation: "EXECUTIVE DIRECTOR PG",
    phone: "01123386203",
    email: "edpg@rb.railnet.gov.in",
    address: "ROOM NO. 509 RAIL BHAVAN RAISINA ROAD NEW DELHI",
  },
  {
    id: "revenue",
    srNo: "71",
    org: "Revenue",
    name: "Shri Manu J Vattickan",
    designation: "Director Coord",
    phone: "01124012460",
    email: "dir-coord-dor@gov.in",
    address: "Kartavya bhawan 1, C wing",
  },
  {
    id: "road-transport-and-highways",
    srNo: "72",
    org: "Road Transport and Highways",
    name: "Shri Lalit Kumar",
    designation: "Director",
    phone: "01123710211",
    email: "lalit.kr@nic.in",
    address: "Room No. 239,Transport Bhawan, Sansad Marg New Delhi",
  },
  {
    id: "rural-development",
    srNo: "73",
    org: "Rural Development",
    name: "Shri Prabhat Kumar",
    designation: "Deputy Secretary",
    phone: "01124360565",
    email: "prabhat.kmr@nic.in",
    address: "Inadia Habitat Centre Core 5A, 2nd Floor, New Delhi",
  },
  {
    id: "school-education-and-literacy",
    srNo: "74",
    org: "School Education and Literacy",
    name: "Shri Subhankar Mishra",
    designation: "Joint Director",
    phone: "01123073542",
    email: "mishra.edu@gov.in",
    address: "Room No. 101-D Wing, Department of School Educatio n and Literacy, Ministry of Human Resource Develo pment,Shastri Bhawan New Delhi",
  },
  {
    id: "science-and-technology",
    srNo: "75",
    org: "Science and Technology",
    name: "Sumona Bhattacharya",
    designation: "Under Secretary PG",
    phone: "01126590462",
    email: "sumona.bhattacharya@gov.in",
    address: "Department of Science and Technology, Technology Bhavan, New Mehrauli Road, New Delhi",
  },
  {
    id: "scientific-and-industrial-research",
    srNo: "76",
    org: "Scientific & Industrial Research",
    name: "Sh. Sanjeev Jain",
    designation: "Deputy Secretary",
    phone: "01126962185",
    email: "sanjeev.jain@nic.in",
    address: "Technology Bhawan, New Mehrauli Road, New Delhi",
  },
  {
    id: "shipping",
    srNo: "77",
    org: "Shipping",
    name: "Sh. Mrityunjay Jha",
    designation: "Director",
    phone: "01123313948",
    email: "mrityunjay.jha@nic.in",
    address: "Room No. 545,Parivahan Bhavan, 1, Sansad Marg New Delhi",
  },
  {
    id: "skill-development-and-entrepreneurship",
    srNo: "78",
    org: "Skill Development and Entrepreneurship",
    name: "Shri Khamchin Naulak",
    designation: "Deputy Secretary",
    phone: "01123465915",
    email: "k.naulak@nic.in",
    address: "2nd Floor, Kaushal Bhawan, New Moti Bagh, New Delhi",
  },
  {
    id: "social-justice-and-empowerment",
    srNo: "79",
    org: "Social Justice and Empowerment",
    name: "Shri Awdhesh Kumar Mehta",
    designation: "Deputy Secretary",
    phone: "01124369837",
    email: "ds-stats-dosje@gov.in",
    address: "Pt. Deendayal Antyodaya Bhawan, CGO Complex, New Delhi.",
  },
  {
    id: "space",
    srNo: "80",
    org: "Space",
    name: "Padma Jyothi S",
    designation: "Deputy Secretary",
    phone: "08022172402",
    email: "pgdos@isro.gov.in",
    address: "Antariksh Bhavan, New B.E.L. Road, Bengaluru",
  },
  {
    id: "sports",
    srNo: "81",
    org: "Sports",
    name: "K.M. Harilal",
    designation: "Director",
    phone: "01123385101",
    email: "km.harilal@nic.in",
    address: "Room No. 7403, 7th Floor, GPOA-03, Netaji Nagar, New Delhi - 110023",
  },
  {
    id: "staff-selection-commission",
    srNo: "82",
    org: "Staff Selection Commission",
    name: "Shri Varinder Singh",
    designation: "Deputy Secretary",
    phone: "01124364795",
    email: "vsingh.71@gov.in",
    address: "Staff Selection Commission, Block No. 12, CGO Complex, Lodhi Road, New Delhi-110003 i",
  },
  {
    id: "statistics-and-programme-implementation",
    srNo: "83",
    org: "Statistics and Programme Implementation",
    name: "Shri Mahesh Chand Beniwal",
    designation: "Deputy Secretary",
    phone: "01123455750",
    email: "mc.beniwal@gov.in",
    address: "Room No. 13, Khurshid Lal Bhawan, Ministry of Stat istics and Programme Implementaion,Janpath, New De lhi",
  },
  {
    id: "steel",
    srNo: "84",
    org: "Steel",
    name: "Ms. Gurpreet Gadhok",
    designation: "Director",
    phone: "01123063355",
    email: "gurpreet.gadhok@nic.in",
    address: "Room No. 63, Udyog Bhavan, New Delhi",
  },
  {
    id: "telecommunications",
    srNo: "85",
    org: "Telecommunications",
    name: "Sh. B M Patel",
    designation: "Director MOC PG",
    phone: "01123220537",
    email: "dirpg.hq-dot@gov.in",
    address: "Room No.605, 6th Floor Mahanagar Doorsanchar Bhawa n Near Zakir Hussain College Old Minto Road New De lhi",
  },
  {
    id: "textiles",
    srNo: "86",
    org: "Textiles",
    name: "Shri Rajeev Ranjan Kumar",
    designation: "Director",
    phone: "01123061142",
    email: "rajeevkumar.dad@gov.in",
    address: "Udyog Bhavan, New Delhi",
  },
  {
    id: "tourism",
    srNo: "87",
    org: "Tourism",
    name: "B.H.T. Vaiphei",
    designation: "Under Secretary",
    phone: "01123713521",
    email: "bht.vaiphei@nic.in",
    address: "Transport Bhawan, 1, Sansad Marg, New Delhi, Delhi",
  },
  {
    id: "tribal-affairs",
    srNo: "88",
    org: "Tribal Affairs",
    name: "Randhir Kumar B. Patel",
    designation: "Director",
    phone: "01123343303",
    email: "randhir.patel@nic.in",
    address: "Ministry of Tribal Affairs, Jeewan Tara Building",
  },
  {
    id: "unique-identification-authority-of-india",
    srNo: "89",
    org: "Unique Identification Authority of India",
    name: "Neeraj Kumar",
    designation: "Director",
    phone: "01123478453",
    email: "dir.crm-hq@uidai.net.in",
    address: "Unique Identification Authority of India, HQ 6th F loor, Bangla Sahib Road Behind Kali Mandir, New De lhi",
  },
  {
    id: "water-resources-river-development-and-ganga-rejuvenuation",
    srNo: "90",
    org: "Water Resources, River Development & Ganga Rejuvenuation,",
    name: "Sankha Roy",
    designation: "Director Coord",
    phone: "01123382448",
    email: "dsea-mowr@nic.in",
    address: "Room No 210 Ground Floor Shastri Bhawan New Delhi",
  },
  {
    id: "women-and-child-development",
    srNo: "91",
    org: "Women and Child Development",
    name: "Shri Aujender Singh",
    designation: "Director",
    phone: "01123380547",
    email: "aujender.singh@nic.in",
    address: "Room No. 641-A, 6th Floor, A Wing, Shastri Bhawan, New Delhi",
  },
  {
    id: "youth-affairs",
    srNo: "92",
    org: "Youth Affairs",
    name: "Madhavi Mohan",
    designation: "Deputy Secretary",
    phone: "01124113206",
    email: "manoj.manu@nic.in",
    address: "Room No. 6107, 6th Floor, Zone-1 GPOA-3 Netaji Nagar, Bhikaji Cama Place, New Delhi",
  },
];

/** Nodal Public Grievance Officers of States and Union Territories. */
export const STATE_NODAL: NodalOfficer[] = [
  {
    id: "andhra-pradesh",
    srNo: "1",
    org: "Andhra Pradesh",
    name: "Chinna Rao",
    designation: "CGO-CMO",
    phone: "09154267973",
    email: "pgrs-helpdesk@ap.gov.in",
    address: "Public Grievance Redressal Cell, CMO Block-01, Gro und Floor, A.P. State Secretariat, Velagapudi, Ama ravathi",
  },
  {
    id: "arunachal-pradesh",
    srNo: "2",
    org: "Arunachal Pradesh",
    name: "Shri Mari Angu",
    designation: "Joint Secretary",
    phone: "03602222222",
    email: "mari.angu@gov.in",
    address: "Civil Secretariat Block No. 04, Floor No. 05, Room No.08, Itanagar",
  },
  {
    id: "assam",
    srNo: "3",
    org: "Assam",
    name: "Shri Utpal Borah ACS",
    designation: "State Nodal Officer",
    phone: "03612237323",
    email: "artassamdept@gmail.com",
    address: "Joint Secretary to the Govt. of Assam, Administrat ive Reforms, Training, Pension and Public Grievanc es Department, Assam Secretariat",
  },
  {
    id: "bihar",
    srNo: "4",
    org: "Bihar",
    name: "Miss Vineeta",
    designation: "DS",
    phone: "06122215409",
    email: "publicgrievances-bih@gov.in",
    address: "General Administration Department, Patna",
  },
  {
    id: "chattisgarh",
    srNo: "5",
    org: "Chattisgarh",
    name: "Shri HEMANT KUMAR PANDEY",
    designation: "UNDER SECRETARY",
    phone: "07712510974",
    email: "pgc-gad.cg@gov.in",
    address: "Public Grievance Redressal Department, Mantralaya Mahanadi Bhavan Nava Raipur Atal nagar",
  },
  {
    id: "goa",
    srNo: "6",
    org: "Goa",
    name: "DIksha N Tari",
    designation: "Under Secretary PG",
    phone: "08322419864",
    email: "us-pgc.goa@nic.in",
    address: "2nd Floor, Secretariat, Porvorim Goa",
  },
  {
    id: "gujarat",
    srNo: "7",
    org: "Gujarat",
    name: "Shri Hareet Shukla",
    designation: "Principal Secretary",
    phone: "07923255969",
    email: "secartd@gujarat.gov.in",
    address: "General Administration Department Block No. 7/3, 3rd Floor, Sachivalaya, Gandhi Nagar",
  },
  {
    id: "haryana",
    srNo: "8",
    org: "Haryana",
    name: "VACANT",
    designation: "Nodal Officer CPGRAMS",
    phone: "01722740226",
    email: "supdt.cpgrams22@gmail.com",
    address: "Chandigarh",
  },
  {
    id: "himachal-pradesh",
    srNo: "9",
    org: "Himachal Pradesh",
    name: "Shainamol A",
    designation: "Secretary - AR RPG Training and FA Ayush",
    phone: "01772620560",
    email: "rpgsecy-hp@nic.in",
    address: "Secretary RPG to the Govt. of HP. Shimla-2.",
  },
  {
    id: "jharkhand",
    srNo: "10",
    org: "Jharkhand",
    name: "Md. Asif Hassan",
    designation: "Joint Secretary",
    phone: "18003456568",
    email: "pgportal.jhr@gmail.com",
    address: "Personnel, Administrative Reforms and Rajhbhasha Department, Jharkhand, Ranchi",
  },
  {
    id: "karnataka",
    srNo: "11",
    org: "Karnataka",
    name: "Suma.S",
    designation: "Under Secretary",
    phone: "08022032214",
    email: "us2dpar-js@karnataka.gov.in",
    address: "Room 211, 2nd Floor, 3rd Gate, M S Building, Beng aluru, G RIEVANCE STATUS LINK https ipgrs.karnataka.gov.in",
  },
  {
    id: "kerala",
    srNo: "12",
    org: "Kerala",
    name: "Sajid M",
    designation: "Under Secretary",
    phone: "04712703002",
    email: "priority.cmo@kerala.gov.in",
    address: "Chief Minister s Computer Cell, 4th Floor, North Block, Government Secretariat, Thiruvananthapura m, Kerala",
  },
  {
    id: "madhya-pradesh",
    srNo: "13",
    org: "Madhya Pradesh",
    name: "Sandeep Asthana",
    designation: "Director CM Helpline",
    phone: "07556680020",
    email: "cmhelpline@mp.gov.in",
    address: "CM Helpline Office, Bhopal, M.P.",
  },
  {
    id: "maharashtra",
    srNo: "14",
    org: "Maharashtra",
    name: "Mr.Hemant Anant Mahajan",
    designation: "Deputy Secretary",
    phone: "02222025101",
    email: "hemant.mahajan@nic.in",
    address: "General Administration Department ,3rd Floor, Mantralaya Mail Building, Mantralaya, Mumbai",
  },
  {
    id: "manipur",
    srNo: "15",
    org: "Manipur",
    name: "K.H. Leiyaphy Rita",
    designation: "Joint Secretary AR",
    phone: "119402882539",
    email: "leiyaphi.kh@gov.in",
    address: "Old Sectt., North Block, Imphal",
  },
  {
    id: "meghalaya",
    srNo: "16",
    org: "Meghalaya",
    name: "Shri Cyril Diengdoh IAS",
    designation: "Commissioner and Secretary Personnel and A.R.",
    phone: "03642500165",
    email: "cyril.diengdoh@gov.in",
    address: "Meghalaya Civil Sectt, Room 403, Additional Building, Shillong, Meghalaya",
  },
  {
    id: "mizoram",
    srNo: "17",
    org: "Mizoram",
    name: "Isaac C. Lalrempuia",
    designation: "Nodal Officer Deptt. of Personnel and Administrative Reforms Good Governance Cell",
    phone: "03892335713",
    email: "ggcmiz@gmail.com",
    address: "Mizoram Secretariat, MINECO, Aizawl",
  },
  {
    id: "nagaland",
    srNo: "18",
    org: "Nagaland",
    name: "Shri Vechovo Tetseo",
    designation: "Senior Research Officer and State Nodal Officer",
    phone: "03700000000",
    email: "vechovo.tetseo@nic.in",
    address: "Nagaland Civil Secretariat, Kohima Kohima",
  },
  {
    id: "nct-of-delhi",
    srNo: "19",
    org: "NCT of Delhi",
    name: "Sh. Upender",
    designation: "Section Officer",
    phone: "01123379900",
    email: "paditi@gmail.com",
    address: "Public Grievances CommissionM Block Vikas Bhawan I P EstateNew Delhi",
  },
  {
    id: "odisha",
    srNo: "20",
    org: "Odisha",
    name: "Deputy Secretary",
    designation: "Deputy Secretary to Government",
    phone: "06742395760",
    email: "gapgpublicgrievance@gmail.com",
    address: "General Administration and Public Grievance Deptt., Odisha Sectt., Bhubaneshwar",
  },
  {
    id: "punjab",
    srNo: "21",
    org: "Punjab",
    name: "IAS",
    designation: "Additional Chief Secretary",
    phone: "01722740611",
    email: "grievanceredressal2@gmail.com",
    address: "Removal Of Grievances Punjab Civil Sectt-1",
  },
  {
    id: "rajasthan",
    srNo: "22",
    org: "Rajasthan",
    name: "Mr Jagdish Lal Meena",
    designation: "Deputy Secretary",
    phone: "01412922825",
    email: "DS.RPG@RAJASTHAN.GOV.IN",
    address: "Room No. 8129, 1st floor, North Western Building, Secretariat Jaipur",
  },
  {
    id: "sikkim",
    srNo: "23",
    org: "Sikkim",
    name: "Shri. Santosh Pradhan",
    designation: "Joint Secretary",
    phone: "035922000000",
    email: "gos.dopart@gmail.com",
    address: "Department of Personnel, Tashiling, Secretariat",
  },
  {
    id: "tamil-nadu",
    srNo: "24",
    org: "Tamil Nadu",
    name: "T. Jeya Sheela B.E MBA",
    designation: "Special Officer",
    phone: "04425671012",
    email: "cmcell@tn.gov.in",
    address: "Chief Ministers Special Cell, Fort St. George, Secretariat Chennai",
  },
  {
    id: "telangana",
    srNo: "25",
    org: "Telangana",
    name: "J.ARUN KUMAR",
    designation: "Additional Secretary to GAD",
    phone: "04023452888",
    email: "dysecy-pgr-gad@telangana.gov.in",
    address: "Dr. B.R. Ambedkar Telangana Secretariat",
  },
  {
    id: "tripura",
    srNo: "26",
    org: "Tripura",
    name: "Smt. Debjani Deb TCS Gr-I",
    designation: "Joint Secretary to the Govt. of Tripura",
    phone: "03812416040",
    email: "gaar.agt-tr@nic.in",
    address: "GAAR Department, Secretariat, New Capital Complex, Kunjaban, Agartala.",
  },
  {
    id: "union-territory-of-andaman-and-nicobar",
    srNo: "27",
    org: "Union Territory of Andaman & Nicobar",
    name: "Smti. B Ganga Ratnam",
    designation: "Assistant Secretary of A.R. Wing and Public Grievances",
    phone: "03192232803",
    email: "asar-trg@and.nic.in",
    address: "Public Grievance Cell A and N Administration, Secretariat, Sri Vijaya Puram",
  },
  {
    id: "union-territory-of-chandigarh",
    srNo: "28",
    org: "Union Territory of Chandigarh",
    name: "Amit Kumar DANICS",
    designation: "Additional Secretary Home",
    phone: "01722994524",
    email: "ashome-chd@chd.gov.in",
    address: "Union Territory Secretariat, Deluxe Building, Sector-9 Chandigarh",
  },
  {
    id: "union-territory-of-dadra-and-nagar-haveli",
    srNo: "29",
    org: "Union Territory of Dadra & Nagar Haveli",
    name: "Dr. Sunabh Singh",
    designation: "Deputy Director-cum-Deputy Secretary",
    phone: "02602230460",
    email: "dshome-dd@ddd.gov.in",
    address: "Department of Public Grievances, Secretariat, Vidyut Bhawan, Kachigam, Nani Daman",
  },
  {
    id: "union-territory-of-daman-and-diu",
    srNo: "30",
    org: "Union Territory of Daman & Diu",
    name: "Dr. Sunabh Singh",
    designation: "Deputy Director-cum-Deputy Secretary",
    phone: "02602230460",
    email: "dshome-dd@ddd.gov.in",
    address: "Department of Public Grievances, Secretariat, Vidyut Bhawan, Kachigam, Nani Daman",
  },
  {
    id: "union-territory-of-jammu-and-kashmir",
    srNo: "31",
    org: "Union Territory of Jammu and Kashmir",
    name: "Azeeta Qureshi",
    designation: "Under Secretary",
    phone: "01942483236",
    email: "qureshi.azee@jk.gov.in",
    address: "H 8 Church Lane, Sonwar Srinagar",
  },
  {
    id: "union-territory-of-ladakh",
    srNo: "32",
    org: "Union Territory of Ladakh",
    name: "Dorjay Gailson JKAS",
    designation: "Nodal Officer for CPGRMS",
    phone: "01982257561",
    email: "gad.utladakh@ladakh.gov.in",
    address: "UT Secretariat Ladakh",
  },
  {
    id: "union-territory-of-lakshadweep",
    srNo: "33",
    org: "Union Territory of Lakshadweep",
    name: "Mukund Vallabh Joshi DANICS",
    designation: "Director",
    phone: "04896262274",
    email: "lak-adps@nic.in",
    address: "Department of Planning, Statistics and TaxationSecretariat, UT of Lakshadweep,Kavaratti, Island",
  },
  {
    id: "union-territory-of-puducherry",
    srNo: "34",
    org: "Union Territory of Puducherry",
    name: "Sivakumar S",
    designation: "Under Secretary ARW",
    phone: "04132233361",
    email: "usar@py.gov.in",
    address: "AR Wing,B Block, 2nd Floor, Chief Sectt., Goubert Avenue, Beach Road,Puducherry",
  },
  {
    id: "uttar-pradesh",
    srNo: "35",
    org: "Uttar Pradesh",
    name: "Shri Bhaskar Chandra Kandpal",
    designation: "Joint Secretary",
    phone: "05222226350",
    email: "bhaskar.31532@gov.in",
    address: "Chief Minister Secretariat , Room No. 321, U.P. Secretariat, Lucknow",
  },
  {
    id: "uttarakhand",
    srNo: "36",
    org: "Uttarakhand",
    name: "Tirath Pal Singh",
    designation: "Additional Director",
    phone: "01352609532",
    email: "cm_helpline@uk.gov.in",
    address: "IT Park, Dehradun",
  },
  {
    id: "west-bengal",
    srNo: "37",
    org: "West Bengal",
    name: "Shri Ajay Kumar Pal",
    designation: "Special Secreta",
    phone: "03322143655",
    email: "jointsecretarypar@gmail.com",
    address: "Nabanna (7th Floor), 325, Sarat Chatterjee Road, Shibpur, Howrah - 711102",
  },
];

/** Nodal Appellate Authorities for CPGRAMS appeals. */
export const APPELLATE: AppellateAuthority[] = [
  {
    id: "central-board-of-direct-taxes-income-tax",
    srNo: "1",
    org: "Central Board of Direct Taxes (Income Tax)",
    name: "Dipi Agarwal",
    designation: "Commissioner of Income Tax _ TPS-II and R",
    phone: "01123416148",
    email: "delhi.dittps@incometax.gov.in",
    address: "Central Board of Direct Taxes Room No 428, 4th Floor Mayur Bhawan, Connaught Circus, New Delhi",
  },
  {
    id: "central-board-of-indirect-taxes-and-customs",
    srNo: "2",
    org: "Central Board of Indirect Taxes and Customs",
    name: "Dr. Shailendra Kumar Sinha",
    designation: "Director General",
    phone: "01123705809",
    email: "shailendra.sinha@gov.in",
    address: "Directorate General of Taxpayer Services, 1st Floor, Central Revenue Building, I.P. Estate, New Delhi",
  },
  {
    id: "department-for-promotion-of-industry-and-internal-trade",
    srNo: "3",
    org: "Department for Promotion of Industry and Internal Trade",
    name: "Jai Prakash Shivahare",
    designation: "Joint Secretary",
    phone: "01123038876",
    email: "js-jps@gov.in",
    address: "Room No. 221, Vanijya Bhavan New Delhi",
  },
  {
    id: "department-of-agriculture-and-farmers-welfare",
    srNo: "4",
    org: "Department of Agriculture and Farmers Welfare",
    name: "Smt. S. Rukmani",
    designation: "Joint Secretary",
    phone: "01123381305",
    email: "s.rukmani@nic.in",
    address: "Department of Agriculture Co-operation and Farmers Welfare Room No. 189, 1st Floor, Krishi Bhavan, New Delhi",
  },
  {
    id: "department-of-agriculture-research-and-education",
    srNo: "5",
    org: "Department of Agriculture Research and Education",
    name: "Gyanendra Dev Tripathi",
    designation: "Additional Secretary",
    phone: "01123384450",
    email: "secy.icar@nic.in",
    address: "Room no. 106, Krishi Bhawan",
  },
  {
    id: "department-of-animal-husbandry-dairying",
    srNo: "6",
    org: "Department of Animal Husbandry, Dairying",
    name: "Dr. Muthukumarasamy B",
    designation: "Joint Secretary",
    phone: "01123382354",
    email: "js-nlm@dahd.nic.in",
    address: "Room No. 190 A, 1st Floor, Krishi Bhawan, New Delhi",
  },
  {
    id: "department-of-atomic-energy",
    srNo: "7",
    org: "Department of Atomic Energy",
    name: "Smt. Nidhi Pandey",
    designation: "Additional Secretary",
    phone: "02222027535",
    email: "as@dae.gov.in",
    address: "Department of Atomic Energy, Anushakti Bhavan, C.S.M. Marg, Mumbai, 400001",
  },
  {
    id: "department-of-bio-technology",
    srNo: "8",
    org: "Department of Bio Technology",
    name: "Ekta Vishnoi",
    designation: "Joint Secretary",
    phone: "01124362982",
    email: "jsadmin.dbt@nic.in",
    address: "Department of Biotechnology, 7th Floor, Room No. 711, Block 2, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "department-of-chemicals-and-petrochemicals",
    srNo: "9",
    org: "Department of Chemicals and Petrochemicals",
    name: "Ms. Divya Parmar",
    designation: "Economic Advisor",
    phone: "01123386752",
    email: "divya.parmar@gov.in",
    address: "Room No. 217, A wing, Shastri Bhawan.",
  },
  {
    id: "department-of-commerce",
    srNo: "10",
    org: "Department of Commerce",
    name: "Ms. Priya Nair",
    designation: "Economic Adviser",
    phone: "01123039556",
    email: "priyanair.10@gov.in",
    address: "Room No. 328, Vanijya Bhawan, New Delhi",
  },
  {
    id: "department-of-consumer-affairs",
    srNo: "11",
    org: "Department of Consumer Affairs",
    name: "MS. M IMKONGLA JAMIR",
    designation: "Joint Secretary",
    phone: "01123381883",
    email: "imkongla.jm@ias.nic.in",
    address: "Department of Consumer Affairs, Krishi Bhawan, New Delhi",
  },
  {
    id: "department-of-defence-finance",
    srNo: "12",
    org: "Department of Defence Finance",
    name: "Shri Ashwini Kumar Tiwari IDAS",
    designation: "Sr. Joint CGDA",
    phone: "01120893004",
    email: "aktiwari68.dad@gov.in",
    address: "Ulan Batar Road, Palam, Delhi Cantt",
  },
  {
    id: "department-of-defence-production",
    srNo: "13",
    org: "Department of Defence Production",
    name: "Ms. Meera Mohanty",
    designation: "Joint Secretary Pers and Coord",
    phone: "01123011553",
    email: "Jscoord-ddp@mod.gov.in",
    address: "Department of Defence Production, Room No.135-A, South Block, New Delhi",
  },
  {
    id: "department-of-defence-research-and-development",
    srNo: "14",
    org: "Department of Defence Research and Development",
    name: "Dr Mayank Dwivedi",
    designation: "Outstanding Scientist and DG-HR",
    phone: "01123016132",
    email: "dghr.hqr@gov.in",
    address: "Room No. 202, DRDO Bhawan, Rajaji Marg, New Delhi",
  },
  {
    id: "department-of-economic-affairs-acc-division",
    srNo: "15",
    org: "Department of Economic Affairs ACC Division",
    name: "Ms. Sakshi Mittal",
    designation: "Joint Secretary",
    phone: "01123095033",
    email: "sakshi.and@nic.in",
    address: "Room No. 15033, 5th Floor, A-Wing, Kartavya Bhavan - l, New Delhi",
  },
  {
    id: "department-of-empowerment-of-persons-with-disabilities",
    srNo: "16",
    org: "Department of Empowerment of Persons with Disabilities",
    name: "Ms. Richa Shankar",
    designation: "Statistical Advisor",
    phone: "01124364394",
    email: "ddg-depwd@gov.in",
    address: "Department of Empowerment of Persons with Disabilities 5th Floor, Pt Deen Dayal Antyodaya Bhawan CGO Complex, New Delhi",
  },
  {
    id: "department-of-ex-servicemen-welfare",
    srNo: "17",
    org: "Department of Ex Servicemen Welfare",
    name: "Shri Pudi Hari Prasad",
    designation: "Joint Secretary (ESW)",
    phone: "01123011804",
    email: "jsesw@nic.in",
    address: "Department of Ex Servicemen Welfare, 99-A South Block, DHQ PO New Delhi",
  },
  {
    id: "department-of-expenditure",
    srNo: "18",
    org: "Department of Expenditure",
    name: "Shri Pradeep Kumar Singh",
    designation: "Joint Secretary E.Coord",
    phone: "01123093290",
    email: "singh.pk@nic.in",
    address: "D/o Expenditure Room No.74-B, North Block, New Delhi",
  },
  {
    id: "department-of-fertilizers",
    srNo: "19",
    org: "Department of Fertilizers",
    name: "Shri Kuntal Sensarma",
    designation: "Sr. Economic Advisor",
    phone: "01124014806",
    email: "Sensarma.kuntal@gov.in",
    address: "23032, Kartavya Bhawan-2, Dr Rajendra Prasad Road, New Delhi 110001",
  },
  {
    id: "department-of-financial-services-banking-division",
    srNo: "20",
    org: "Department of Financial Services (Banking Division)",
    name: "Sh HARI HAR MISHRA",
    designation: "ADDITIONAL SECRETARY",
    phone: "01123346785",
    email: "mishrahh@nic.in",
    address: "Department of Financial Services, Jeevan Deep Builiding, New Delhi",
  },
  {
    id: "department-of-financial-services-insurance-division",
    srNo: "21",
    org: "Department of Financial Services (Insurance Division)",
    name: "Sh Harihar Mishra",
    designation: "Additional Secretary",
    phone: "01123346785",
    email: "mishrahh@nic.in",
    address: "Department of Financial Services, Jeevan Deep Builiding, New Delhi",
  },
  {
    id: "department-of-financial-services-pension-reforms",
    srNo: "22",
    org: "Department of Financial Services (Pension Reforms)",
    name: "Shri Samir Kumar",
    designation: "Economic Advisor",
    phone: "01123748774",
    email: "ea1-dfs@gov.in",
    address: "Department of Financial Services - Pension Reforms, Room No. 3, 3rd Floor, Jeevan Deep Building, Sansad Marg, New Delhi",
  },
  {
    id: "department-of-fisheries",
    srNo: "23",
    org: "Department of Fisheries",
    name: "Sagar Mehra",
    designation: "Joint Secretary",
    phone: "011-23383781",
    email: "sagar.mehra@nic.in",
    address: "Room No. 482 Krishi Bhawan New Delhi",
  },
  {
    id: "department-of-food-and-public-distribution",
    srNo: "24",
    org: "Department of Food and Public Distribution",
    name: "Ms. Nandita Mishra",
    designation: "Sr. Economic Advisor",
    phone: "01123070371",
    email: "nandita.mishra@nic.in",
    address: "Department of Food and Public Distribution Room No.194, Krishi Bhawan, New Delhi",
  },
  {
    id: "department-of-health-and-family-welfare",
    srNo: "25",
    org: "Department of Health & Family Welfare",
    name: "Sh Elangbam Robert Singh",
    designation: "Joint Secretary",
    phone: "01123063276",
    email: "Robert.elangbam@gov.in",
    address: "Department of Health and Family Welfare, Nirman Bhawan, New Delhi",
  },
  {
    id: "department-of-health-research",
    srNo: "26",
    org: "Department of Health Research",
    name: "Shri Dhananjay Prasad Singh",
    designation: "Deputy Secretary",
    phone: "01123736218",
    email: "dpsingh@gov.in",
    address: "Department of Health Research, Room No. 225, Indian Red Cross Society Building, 1, Red Cross Road, NEW DELHI",
  },
  {
    id: "department-of-higher-education",
    srNo: "27",
    org: "Department of Higher Education",
    name: "Sh. Ashish V Gawai",
    designation: "Joint Secretary",
    phone: "01124015032",
    email: "js.pmusha@nic.in",
    address: "Room no. 22032, Kartavaya Bhawan- 2, M/o Education, D/o Higher Education,New Delhi",
  },
  {
    id: "department-of-investment-and-public-asset-management",
    srNo: "28",
    org: "Department of Investment & Public Asset Management",
    name: "Dr. Arunish Chawla",
    designation: "Secretary",
    phone: "01124368040",
    email: "secydivest@nic.in",
    address: "DIPAM Room No.407 , 4th Floor Block No. 14 CGO Complex, Lodhi Road New Delhi",
  },
  {
    id: "department-of-justice",
    srNo: "29",
    org: "Department of Justice",
    name: "Suresh Kumar",
    designation: "Joint Secretary",
    phone: "01123072142",
    email: "jsnm-jr-doj@gov.in",
    address: "26, MAN SINGH ROAD, NEW DELHI",
  },
  {
    id: "department-of-land-resources",
    srNo: "30",
    org: "Department of Land Resources",
    name: "Shri P K Abdul Kareem",
    designation: "Economic Adviser",
    phone: "01123062454",
    email: "pka.kareem@nic.in",
    address: "Department of Land Resources, Room No. 12, Ground Floor, NBO Building, Nirman Bhawan, New Delhi",
  },
  {
    id: "department-of-military-affairs",
    srNo: "31",
    org: "Department of Military Affairs",
    name: "Mr. Anil Kumar Chhapolia",
    designation: "Joint Secretary - Estt and Coord",
    phone: "01123011410",
    email: "jsg@nic.in",
    address: "Department of Military Affairs, Room No.97, South Block, New Delhi",
  },
  {
    id: "department-of-official-language",
    srNo: "32",
    org: "Department of Official Language",
    name: "Dr. Nidhi Pandey",
    designation: "Joint Secretary",
    phone: "01123438130",
    email: "jsol@mha.gov.in",
    address: "NDCC-II Building, 4th Floor, Jai Singh Road, New Delhi",
  },
  {
    id: "department-of-pension-and-pensioners-welfare",
    srNo: "33",
    org: "Department of Pension and Pensioners Welfare",
    name: "Dr. Pramod Kumar",
    designation: "Director",
    phone: "01124654734",
    email: "pramod.kumar79@gov.in",
    address: "DoPPW",
  },
  {
    id: "department-of-personnel-and-training",
    srNo: "34",
    org: "Department of Personnel and Training",
    name: "Shri S D Sharma",
    designation: "Joint Secretary",
    phone: "01124010567",
    email: "js.admn-dopt@gov.in",
    address: "Room No. 31035, Kartavya Bhavan-03, New Delhi",
  },
  {
    id: "department-of-pharmaceuticals",
    srNo: "35",
    org: "Department of Pharmaceuticals",
    name: "Sh. Aman Sharma",
    designation: "Joint Secretary",
    phone: "01123074010",
    email: "head-coordination@pharma-dept.gov.in",
    address: "348, A Wing Shastri Bhawan New Delhi-110001",
  },
  {
    id: "department-of-posts",
    srNo: "36",
    org: "Department of Posts",
    name: "Ms. Mrinalini Srivastava",
    designation: "DDG PG QA and I",
    phone: "01123096088",
    email: "ddgpgq@indiapost.gov.in",
    address: "Dak Bhawan",
  },
  {
    id: "department-of-revenue",
    srNo: "37",
    org: "Department of Revenue",
    name: "Shri Balasubramanian Krishnamurthy",
    designation: "Joint Secretary",
    phone: "01123095358",
    email: "jsrev@gov.in",
    address: "D/o Revenue, Room No. 46, North Block, New Delhi",
  },
  {
    id: "department-of-rural-development",
    srNo: "38",
    org: "Department of Rural Development",
    name: "Ms. Kalyani Mishra",
    designation: "Economic Advisor",
    phone: "01123386173",
    email: "eansap-mord@nic.in",
    address: "Ministry of Rural Development, DoRD India Habitat Centre, New Delhi",
  },
  {
    id: "department-of-school-education-and-literacy",
    srNo: "39",
    org: "Department of School Education and Literacy",
    name: "DR. AMARPREET DUGGAL",
    designation: "Joint Secretary Coord",
    phone: "01123386232",
    email: "jsad-moe@gov.in",
    address: "Room No.107 A-D Wing, Shastri Bhawan, New Delhi",
  },
  {
    id: "department-of-science-and-technology",
    srNo: "40",
    org: "Department of Science and Technology",
    name: "A Dhanalakshmi",
    designation: "Joint Secretary",
    phone: "01126516077",
    email: "a.dhanlakshmi@nic.in",
    address: "Department of Science and Technology, Technology Bhavan, New Mehrauli Road, New Delhi-110016",
  },
  {
    id: "department-of-scientific-and-industrial-research",
    srNo: "41",
    org: "Department of Scientific & Industrial Research",
    name: "Shri Surinder Pal Singh",
    designation: "Joint Secretary",
    phone: "01126590257",
    email: "surinder.singh66@gov.in",
    address: "Room No. 517, 5th Floor, DST/DSIR Building, Technology Bhawan, Mehrauli Road, New Delhi",
  },
  {
    id: "department-of-social-justice-and-empowerment",
    srNo: "42",
    org: "Department of Social Justice and Empowerment",
    name: "Shri Vinesh Pachnanda",
    designation: "Deputy Secretary",
    phone: "01124369837",
    email: "vinesh.pachnanda@nic.in",
    address: "Pt. Deendayal Antyodaya Bhawan, CGO Complex, New Delhi.",
  },
  {
    id: "department-of-space",
    srNo: "43",
    org: "Department of Space",
    name: "Swarnashree Rao Rajashekar",
    designation: "Joint Secretary Personnel",
    phone: "08022175401",
    email: "pgdos@isro.gov.in",
    address: "Department of Space Antriksh Bhawan New B.E.L.Road Bengaluru",
  },
  {
    id: "department-of-sports",
    srNo: "44",
    org: "Department of Sports",
    name: "Sh. Kunal JS",
    designation: "JSSports Development",
    phone: "01123384152",
    email: "js-develop-sports@gov.in",
    address: "D/o Sports Room No. 504-B, Shastri Bhawan, New Delhi",
  },
  {
    id: "department-of-telecommunications",
    srNo: "45",
    org: "Department of Telecommunications",
    name: "Sh Jayant Kumar",
    designation: "Sr Deputy Director General - Public Grievances",
    phone: "01123221231",
    email: "ddgpg-dot@nic.in",
    address: "Department of TelecommunicationsRoom No 612, Manager DoorsancharBhawan,Old Minto Road, New Delhi",
  },
  {
    id: "department-of-youth-affairs",
    srNo: "46",
    org: "Department of Youth Affairs",
    name: "Shiv Ratan",
    designation: "Joint Secretary",
    phone: "01124103299",
    email: "js.dya@gov.in",
    address: "Ministry of Youth Affairs and Sports, Room No. 6204, Netaji Nagar, New Delhi",
  },
  {
    id: "legislative-department",
    srNo: "47",
    org: "Legislative Department",
    name: "T S Muralidharan",
    designation: "Joint Secretary & Legislative Counsel",
    phone: "01124016064",
    email: "muralidharan.ts@nic.in",
    address: "Room No. 24005, 4th Floor, Kartavya Bhavan 2, New Delhi",
  },
  {
    id: "ministry-of-ayush",
    srNo: "48",
    org: "Ministry of Ayush",
    name: "Dr. M.A. Qasmi",
    designation: "Adviser Unani",
    phone: "01124651966",
    email: "mukhtar.qasmi@gov.in",
    address: "Ministry of Ayush, AYUSH BHAWAN, B Block, GPO Complex, INA, New Delhi",
  },
  {
    id: "ministry-of-civil-aviation",
    srNo: "49",
    org: "Ministry of Civil Aviation",
    name: "Ms. Priyanka Das",
    designation: "Joint Secretary",
    phone: "01124616303",
    email: "aapg-moca@gov.in",
    address: "M/o Civil Aviation, Room No.354, 3rd floor Floor, B-Block,Rajiv Gandhi Bhawan, Safdarjung Airport,New Delhi",
  },
  {
    id: "ministry-of-cooperation",
    srNo: "50",
    org: "Ministry of Cooperation",
    name: "Shri Pankaj Kumar Bansal",
    designation: "Additional Secretary",
    phone: "01120849005",
    email: "bansalpk@ias.nic.in",
    address: "Delhi",
  },
  {
    id: "ministry-of-corporate-affairs",
    srNo: "51",
    org: "Ministry of Corporate Affairs",
    name: "Sh. Kailash Chand Meena",
    designation: "Director Public Grievances",
    phone: "01123389602",
    email: "santosh.kumar@mca.gov.in",
    address: "Ministry of Corporate Affairs, Shastri Bhawan , New Delhi at -DGCoA Kota House , New Delhi",
  },
  {
    id: "ministry-of-culture",
    srNo: "52",
    org: "Ministry of Culture",
    name: "Gurmeet Singh Chawla",
    designation: "Joint Secretary",
    phone: "01123075342",
    email: "gurmeet.chawla@gov.in",
    address: "ASI HQ",
  },
  {
    id: "ministry-of-development-of-north-eastern-region",
    srNo: "53",
    org: "Ministry of Development of North Eastern Region",
    name: "Mr. Nilambuj Sharan",
    designation: "Sr. Economic Adviser",
    phone: "011-23022386",
    email: "nilambuj.sharan@nic.in",
    address: "M/o Development of North East Region, Vigyan Bhawan Annexe, New Delhi",
  },
  {
    id: "ministry-of-drinking-water-and-sanitation",
    srNo: "54",
    org: "Ministry of Drinking Water and Sanitation",
    name: "Shri Vikash Kumar Dubey",
    designation: "Deputy Director General",
    phone: "01124369832",
    email: "vikash.dubey@nic.in",
    address: "6th floor, Pt. Deendayal Antyodaya Bhawan, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "ministry-of-earth-sciences",
    srNo: "55",
    org: "Ministry of Earth Sciences",
    name: "Sreenivasa Rao Gangi Reddy",
    designation: "Joint Secretary",
    phone: "01124629528",
    email: "js@moes.gov.in",
    address: "Ministry of Earth Science Room No.102, Prithvi Bhawan, Lodhi Road, New Delhi",
  },
  {
    id: "ministry-of-electronics-and-information-technology",
    srNo: "56",
    org: "Ministry of Electronics & Information Technology",
    name: "Sh. Sudeep Shrivastava",
    designation: "Joint Secretary and GC",
    phone: "01124301815",
    email: "s.sudeep@gov.in",
    address: "6, CGO Complex, Electronics Niketan, New Delhi",
  },
  {
    id: "ministry-of-environment-forest-and-climate-change",
    srNo: "57",
    org: "Ministry of Environment, Forest and Climate Change",
    name: "Shri Satyajit Mishra",
    designation: "Joint Secretary",
    phone: "01120819232",
    email: "satyajit.mishra@nic.in",
    address: "1st Floor, Agni Wing, Indira Paryawaran Bhawan, Jor Bagh, New Delhi",
  },
  {
    id: "ministry-of-external-affairs",
    srNo: "58",
    org: "Ministry of External Affairs",
    name: "Dr. Binoy George",
    designation: "Joint Secretary CPV",
    phone: "01123384529",
    email: "jscpv@mea.gov.in",
    address: "Ministry of External Affairs, CPV Division, Patiala House Annexe, TilakMarg, New Delhi",
  },
  {
    id: "ministry-of-food-processing-industries",
    srNo: "59",
    org: "Ministry of Food Processing Industries",
    name: "Shri Ranjit Singh",
    designation: "Joint Secretary",
    phone: "01126492176",
    email: "singhranjit@cag.gov.in",
    address: "Ministry of Food Processing Industries, Panchsheel Bhawan, August Kranti Marg, New Delhi",
  },
  {
    id: "ministry-of-heavy-industries",
    srNo: "60",
    org: "Ministry of Heavy Industries",
    name: "Dr Renuka Mishra",
    designation: "Economic Adviser",
    phone: "01123062714",
    email: "ea.dhi@nic.in",
    address: "Department of Heavy Industries Room No. 123-B, Udyog Bhawan New Delhi",
  },
  {
    id: "ministry-of-home-affairs",
    srNo: "61",
    org: "Ministry of Home Affairs",
    name: "ARVIND KHARE",
    designation: "Jt. Secretary Co-ord",
    phone: "01124010034",
    email: "jscpg-mha@nic.in",
    address: "34089 4th Floor Kartavya Bhavan-3",
  },
  {
    id: "ministry-of-housing-and-urban-affairs",
    srNo: "62",
    org: "Ministry of Housing and Urban Affairs",
    name: "Shri Dinesh Kapila",
    designation: "EA",
    phone: "01123062387",
    email: "dinesh.kapila@nic.in",
    address: "Room No. 232-C,Nirman Bhawan, New Delh",
  },
  {
    id: "ministry-of-information-and-broadcasting",
    srNo: "63",
    org: "Ministry of Information and Broadcasting",
    name: "Shri Rabindra Kumar Jena",
    designation: "Senior Economic Adviser",
    phone: "01123383857",
    email: "rk.jena@gov.in",
    address: "Room No. 657, A Wing, Shastri Bhawan, New Delhi",
  },
  {
    id: "ministry-of-labour-and-employment",
    srNo: "64",
    org: "Ministry of Labour and Employment",
    name: "Shefali Dhingra",
    designation: "Economic Advisor",
    phone: "01123737510",
    email: "ecoadvisor-mole@gov.in",
    address: "Ministry of Labour and Employment, Room No.312, Shram Shakti Bhawan, Rafi Marg,New Delhi",
  },
  {
    id: "ministry-of-micro-small-and-medium-enterprises",
    srNo: "65",
    org: "Ministry of Micro Small and Medium Enterprises",
    name: "Sh. Ateesh Kumar Singh",
    designation: "Joint Secretary",
    phone: "01123062081",
    email: "js-msme@gov.in",
    address: "Ministry of Micro Small and Medium Enterprises Room No. 49, Ground Floor Udyog Bhawan New Delhi",
  },
  {
    id: "ministry-of-mines",
    srNo: "66",
    org: "Ministry of Mines",
    name: "Smt Sushama Batra",
    designation: "Deputy Secretary- PG&PI",
    phone: "01123382159",
    email: "sushma.batra@gov.in",
    address: "Zone 3, 4th Floor, GPOA-3 Building, Netaji Nagar, New Delhi",
  },
  {
    id: "ministry-of-minority-affairs",
    srNo: "67",
    org: "Ministry of Minority Affairs",
    name: "Shri Shyama Prasad Roy",
    designation: "Joint Secretary",
    phone: "01124364270",
    email: "ddg-mma@gov.in",
    address: "Ministry of Minority Affairs , Pt Deen Dayal Antoydaya Bhawan, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "ministry-of-new-and-renewable-energy",
    srNo: "68",
    org: "Ministry of New and Renewable Energy",
    name: "Mini Prasannakumar",
    designation: "DDG",
    phone: "01120849138",
    email: "miniprasanna.k@nic.in",
    address: "Room No. 615, AAUB, Opposite CGO Complex, Lodhi Road",
  },
  {
    id: "ministry-of-panchayati-raj",
    srNo: "69",
    org: "Ministry of Panchayati Raj",
    name: "Shri Rajesh Kumar Singh",
    designation: "Joint Secretary",
    phone: "01123725305",
    email: "mopr-js@gov.in",
    address: "9th Floor, Jeevan Bharati Building, New Delhi",
  },
  {
    id: "ministry-of-parliamentary-affairs",
    srNo: "70",
    org: "Ministry of Parliamentary Affairs",
    name: "Dr. Satya Prakash",
    designation: "Additional Secretary",
    phone: "01123034734",
    email: "asmpa@gov.in",
    address: "R.No.87, Parliament House,New Delhi",
  },
  {
    id: "ministry-of-petroleum-and-natural-gas",
    srNo: "71",
    org: "Ministry of Petroleum and Natural Gas",
    name: "RTI PG Section",
    designation: "DS PG",
    phone: "01122488624",
    email: "pande.ravi04@nic.in",
    address: "Shastri Bhawan,New Delhi",
  },
  {
    id: "ministry-of-power",
    srNo: "72",
    org: "Ministry of Power",
    name: "Smt. Reetu Jain",
    designation: "Economic Adviser",
    phone: "01123715378",
    email: "ea-mop@gov.in",
    address: "Room No. 427, C-Wing, Ministry of Power, Shram Shakti Bhawan, Rafi Marg, New Delhi",
  },
  {
    id: "ministry-of-railways-railway-board",
    srNo: "73",
    org: "Ministry of Railways ( Railway Board)",
    name: "Shri Deepak Kumar Jha",
    designation: "Additional Member Commercial",
    phone: "01123382112",
    email: "amc@rb.railnet.gov.in",
    address: "Ministry of Railways , Rail Bhawan New Delhi",
  },
  {
    id: "ministry-of-road-transport-and-highways",
    srNo: "74",
    org: "Ministry of Road Transport and Highways",
    name: "Sh. C.N. Singh",
    designation: "Joint Secretary",
    phone: "01123753991",
    email: "js.morth@gov.in",
    address: "Room No. 322 , Transport Bhawan,Sansad Marg, New Delhi",
  },
  {
    id: "ministry-of-shipping",
    srNo: "75",
    org: "Ministry of Shipping",
    name: "Sh. Sandeep Kumar Gupta",
    designation: "Joint Secretary -Coordination",
    phone: "01123354007",
    email: "jsadmin-psw@gov.in",
    address: "New Delhi",
  },
  {
    id: "ministry-of-skill-development-and-entrepreneurship",
    srNo: "76",
    org: "Ministry of Skill Development and Entrepreneurship",
    name: "Ms. Archana Mayaram",
    designation: "Economic Advisor",
    phone: "01126773311",
    email: "archana.mayaram@gov.in",
    address: "Ministry of Skill Development and Entrepreneurship Room No.311, Kaushal Bhawan, New Moti Bagh, New Delhi",
  },
  {
    id: "ministry-of-statistics-and-programme-implementation",
    srNo: "77",
    org: "Ministry of Statistics and Programme Implementation",
    name: "Sh. Aashish Kumar Gupta",
    designation: "JOINT SECRETARY",
    phone: "01123455325",
    email: "akgupta2@ord.gov.in",
    address: "Ministry of Statistics and Programme Implementation, Room no. 309, Khurshid Lal Bhawan, Janpath, New Delhi",
  },
  {
    id: "ministry-of-steel",
    srNo: "78",
    org: "Ministry of Steel",
    name: "Shri Daya Nidhan Pandey",
    designation: "Joint Secretary",
    phone: "01123063170",
    email: "dn.pandey74@ias.nic.in",
    address: "Ministry of Steel Udyog Bhawan, New Delhi",
  },
  {
    id: "ministry-of-textiles",
    srNo: "79",
    org: "Ministry of Textiles",
    name: "Shri Akhilesh Kumar",
    designation: "Deputy Director General",
    phone: "01123062109",
    email: "akhilesh.kumar99@gov.in",
    address: "Udyog Bhawan, New Delhi",
  },
  {
    id: "ministry-of-tourism",
    srNo: "80",
    org: "Ministry of Tourism",
    name: "Venkatramana R. Hegde",
    designation: "Additional Director General",
    phone: "01123724165",
    email: "v.hegde@nic.in",
    address: "3nd Floor PTI Building, Sansad Marg, New Delhi, Delhi 110001",
  },
  {
    id: "ministry-of-tribal-affairs",
    srNo: "81",
    org: "Ministry of Tribal Affairs",
    name: "Ms. Athira S. Babu",
    designation: "Economic Advisor",
    phone: "01123340005",
    email: "athira.babu@gov.in",
    address: "Ministry of Tribal Affair, Jeevan Tara Building, New Delhi",
  },
  {
    id: "ministry-of-water-resources-river-development-and-ganga-rejuvenation",
    srNo: "82",
    org: "Ministry of Water Resources, River Development & Ganga Rejuvenation",
    name: "Shri Karan Singh",
    designation: "Joint Secretary A IC and GW",
    phone: "01123714609",
    email: "jsadmn-mowr@nic.in",
    address: "Room No 403, Shram Shakti Bhawan, New Delhi",
  },
  {
    id: "ministry-of-women-and-child-development",
    srNo: "83",
    org: "Ministry of Women and Child Development",
    name: "Shri Valeti Premchand",
    designation: "Additional Secretary",
    phone: "01123380641",
    email: "premchand.v@gov.in",
    address: "Room No. 628 A, Shastri Bhawan , Ministry of Woman and Child Development New Delhi",
  },
  {
    id: "niti-aayog",
    srNo: "84",
    org: "NITI Aayog",
    name: "Shri K S Rejimon",
    designation: "Joint Secretary",
    phone: "01123096545",
    email: "ks.rejimon@nic.in",
    address: "RoomNo. 233 NITI Aayog, Sansad Marg, New Delhi",
  },
  {
    id: "o-o-the-comptroller-and-auditor-general-of-india",
    srNo: "85",
    org: "O/o the Comptroller & Auditor General of India",
    name: "SHRI SAURABH NARAIN",
    designation: "Director General",
    phone: "01123236776",
    email: "dgstaff@cag.gov.in",
    address: "O/o the Comptroller And Auditor General of India, 9, Deen Dayal Upadhayaya Marg, New Delhi",
  },
  {
    id: "securities-and-exchange-board-of-india",
    srNo: "86",
    org: "Securities and Exchange Board of India",
    name: "Shri Krishnanand Raghavan",
    designation: "Chief General Manager",
    phone: "02226449632",
    email: "krishnanandr@sebi.gov.in",
    address: "OIAE-IGRD, Securities and Exchange Board of India SEBI Bhavan, II BKC, Plot No. C-7, G Block, Bandra Kurla Complex, Bandra East, Mumbai, Maharashtra",
  },
  {
    id: "staff-selection-commission",
    srNo: "87",
    org: "Staff Selection Commission",
    name: "Sh. RAJIV SRIVASTAVA",
    designation: "Member",
    phone: "01124362242",
    email: "member1@ssc.nic.in",
    address: "Block No. 12, CGO Complex, Lodhi Road, New Delhi",
  },
  {
    id: "unique-identification-authority-of-india",
    srNo: "88",
    org: "Unique Identification Authority of India",
    name: "Shri Neeraj Kumar",
    designation: "Director CRM Division",
    phone: "01123478453",
    email: "dir.crm-hq@uidai.net.in",
    address: "Unique Identification Authority of India, 6th Floor, UIDAI Headquarter Building, Bangla Sahib Road, Gole Market, New Delhi",
  },
];
